version: '2.1'

services:
  mai-db-node-ex01:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: mai-db-node-ex01
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3360:3306
    healthcheck:
      test: "/usr/bin/mysql --user=stud --password=stud --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    volumes:
      - db-node-ex01-data:/var/lib/mysql

  grpc-server-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc-server-1
    environment:
      - DB_HOST=mai-db-node-ex01
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
      - SERVER_NAME=grpc-server-1
    ports:
      - 50051:50051
    networks:
      - arch-network
    depends_on:
      mai-db-node-ex01:
        condition: service_healthy

  grpc-server-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc-server-2
    environment:
      - DB_HOST=mai-db-node-ex01
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
      - SERVER_NAME=grpc-server-2
    ports:
      - 50052:50051
    networks:
      - arch-network
    depends_on:
      mai-db-node-ex01:
        condition: service_healthy 
  haproxy:
    image: haproxy
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - 3001:3001
    depends_on:
      - grpc-server-1
      - grpc-server-2
    networks:
      - arch-network

volumes:
  db-node-ex01-data:

networks:
  arch-network:
    driver: "bridge"
    external: false